# Generated by Django 5.2.15 on 2026-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
